import localFont from "next/font/local";
import Header from "@components/molecules/header/index.jsx";
import "@app/globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Rodape from "@components/organisms/rodape";
import Clarity from "@microsoft/clarity";
import ProgressBar from "@components/molecules/progress-bar";

const lexend = localFont({
  display: "swap",
  variable: "--font-lexend",
  src: [
    {
      path: "../../public/fonts/Lexend-Black.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lexend-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lexend-ExtraBold.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lexend-ExtraLight.woff",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lexend-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lexend-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lexend-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lexend-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lexend-Thin.woff",
      weight: "100",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const projectId = "smzu0vvj7r";
  Clarity.init(projectId);
  return (
    <html lang="pt-BR" className={`w-full ${lexend.variable} relative`}>
      <body className="font-lexend flex flex-col items-center w-full estrutura-container gap-[50px] pb-5">
        <ProgressBar>
          <SpeedInsights />
          <Header />
          <div className="estrutura-padding flex flex-col items-center w-full gap-[50px]">
          {children}
          </div>
          <Rodape />
        </ProgressBar>
      </body>
    </html>
  );
}
